import Elementary

/// Controls the CSS `cursor` property.
public enum TWTCursor: String, TWToken, Sendable, Equatable, CaseIterable {
    case auto = "cursor-auto"
    case `default` = "cursor-default"
    case pointer = "cursor-pointer"
    case wait = "cursor-wait"
    case text = "cursor-text"
    case move = "cursor-move"
    case help = "cursor-help"
    case notAllowed = "cursor-not-allowed"
    case none = "cursor-none"
    case contextMenu = "cursor-context-menu"
    case progress = "cursor-progress"
    case cell = "cursor-cell"
    case crosshair = "cursor-crosshair"
    case verticalText = "cursor-vertical-text"
    case alias = "cursor-alias"
    case copy = "cursor-copy"
    case noDrop = "cursor-no-drop"
    case grab = "cursor-grab"
    case grabbing = "cursor-grabbing"
    case colResize = "cursor-col-resize"
    case rowResize = "cursor-row-resize"
    case nResize = "cursor-n-resize"
    case eResize = "cursor-e-resize"
    case sResize = "cursor-s-resize"
    case wResize = "cursor-w-resize"
    case neResize = "cursor-ne-resize"
    case nwResize = "cursor-nw-resize"
    case seResize = "cursor-se-resize"
    case swResize = "cursor-sw-resize"
    case ewResize = "cursor-ew-resize"
    case nsResize = "cursor-ns-resize"
    case neswResize = "cursor-nesw-resize"
    case nwseResize = "cursor-nwse-resize"
    case zoomIn = "cursor-zoom-in"
    case zoomOut = "cursor-zoom-out"
}
